### PR TITLE
Update simple viewer example

### PR DESCRIPTION
**Pull request by jamie-lemon**
Does the following:

- Addresses some of the top level TODOs in the project
- Moves CSS to dedicated file
- Renames a JS file to match its class name
- Indents the HTML file to make it more readable

### CODE REVIEW

**Comment by ccxvii** [comment]
I don't think we should split the files for a couple of reasons:

It adds to latency when loading (needs one more HTTP round-trip to check the cache status of the sub-resource).

It leads to possible synchronization issues when the browser uses stale cached files. Using the HTML with mis-matching JS or CSS styles. Happens all the time unless you're super careful about setting the correct cache-control headers (and even then you run into problems with Safari), or use annoying cache-busting schemes. 

Splitting the viewer client source up into a file per class, where some of the files depend on the code in the other files, only works when combining the source text using <script> tags. When using modules (as I expect we'll want to do in the future) each file has its own namespace and then will need to cross-import each other. That way lies insanity.

**Comment by ccxvii** [comment]
If you split the page number (+1 / -1) fixes into a separate PR we can get that change merged.

**Comment by jamie-lemon** [comment]
Surely the external CSS file and tab indentation for the HTML file makes sense?

**Comment by jamie-lemon** [comment]
This is just an example though isn't it which we encourage people to run locally in the README? The split files are better for readability and understanding of the structure and what is going on where.

Probably it is better to add a note about what you mention for deployment environments. i.e. a disclaimer for the developer - they should consider latency etc, add async load waits for the JS files etc.

**Comment by ccxvii** [comment]
How is needing to open and juggle multiple files to read a simple example EASIER than having everything related in one place right next to where it's used?

**Pull request closed without merging**
