### PR TITLE
Improve search functionality

### PR DESCRIPTION
**Pull request by xybei**
* Addresses issues #78 & #98 
  Fix the issue where the search results on the current page would be skipped when clicking the "Next" search button for the first time. 
  Improve the search experience for the Chinese input method.

* Add an Enter key handler for the search input. 
  Enter: search "Next"
  Shift + Enter: search "Prev"

* Display page number based on 1

### CODE REVIEW

**Comment by xybei** [comment]
I have read the CLA Document and I hereby sign the CLA

**Review by jamie-lemon — CHANGES_REQUESTED** [review]
This works great! Nice and succinct and solves the problem we were having with the input listener. One small thing though - the user needs to "know" to press the "Enter" key. Believe it or not not all users will "know" this. Especially if they are on a tablet or phone and just dismiss their virtual keyboard, "what next?", might be the thought.
For this reason and think it is also better to include a dedicated search button ( or icon ) which does the same as "Enter". Please consider this and update!

**Comment by xybei** [comment]
Thanks for the quick reply.
I investigated Acrobat, Chrome, pdf.js, and VS Code, they all employ two buttons for searching. They support pressing `Enter` to find the next one and `Shift+Enter` to find the previous one (Acrobat not supporting `Shift+Enter`). 


image
image
image
image

I think users are already accustomed to this operation. Even if users are unaware of the `Enter` key, clicking `Next` will still function correctly. 
The virtual keyboard on a tablet or phone also has an `Enter` key, or even if it doesn't, the `Prev` or `Next` buttons still perform adequately—`Enter` merely acts as an accelerator.

If you are concerned that `Next` might cause confusion, how about considering changing it to `<` and `>` like other readers? 
(I think the original `Prev` and `Next` are adequate.)

Here are a few character icons:
```html
<button id="search-prev" onclick="run_search(-1, 1)">Prev</button>
<button id="search-next" onclick="run_search(1, 1)">Next</button>
<button id="search-prev" onclick="run_search(-1, 1)">&#x3C;</button>
<button id="search-next" onclick="run_search(1, 1)">&#x3E;</button>
<button id="search-prev" onclick="run_search(-1, 1)">&#x2227;</button>
<button id="search-next" onclick="run_search(1, 1)">&#x2228;</button>
<button id="search-prev" onclick="run_search(-1, 1)">&#x22C0;</button>
<button id="search-next" onclick="run_search(1, 1)">&#x22C1;</button>
<button id="search-prev" onclick="run_search(-1, 1)">&#x25B2;</button>
<button id="search-next" onclick="run_search(1, 1)">&#x25BC;</button>
```
They appear as follows: (Which one do you think looks better?)
image

Are you still considering adding a dedicated `Search` button? If so, I think your pull request #111 will be satisfactory.

**Comment by jamie-lemon** [comment]
@xybei Excellent research and much appreciated! I think if we go with `&#x3C;` and `&#x3E;` for prev & next then we are all good - being language agnostic makes sense here. Can you update with a new commit for this? After that I will squash & merge!

**Comment by xybei** [comment]
Sure, I'll submit an update later, thanks!

**Review by jamie-lemon — APPROVED** [review]

**Pull request merged**
